// ignore_for_file: prefer_const_constructors, file_names
//TODO ID IS COMMING NULL. THEREFORE UPDATE, DELETE NOT WORKING. AUTOINCREMENT NOT WORKING.

//! PROBLEM, ID IS NOT BEING SAVED IN DATABASE.
//? DEETE IS A CORRECT STATEMENT. NOT WORKING BCOZ NO ID IS BEING SAVED
//? I THINK WE PREDEFINED ID IN SQL3. SO NOT AUTOGENERATED
//// STUPID:- BUT WHY WAS IT THEN RETURNING IN QUERY IN SQL3?? => bcoz i specified the id.
//?

import 'package:flutter/material.dart';
import 'package:sqffflittte4/database_helper.dart';

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final DBManager dbManager = DBManager();
  final _nameController = TextEditingController();
  final _courseController = TextEditingController();
  final _formKey = GlobalKey<FormState>();
  Student? student;
  List<Student>? studlist;
  int? updateIndex;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("SQFlite Demo"),
      ),
      body: ListView(
        children: [
          Form(
            key: _formKey,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Column(
                children: [
                  TextFormField(
                    controller: _nameController,
                    decoration: InputDecoration(labelText: 'Name'),
                    validator: (val) =>
                        val!.isNotEmpty ? null : 'Name Should Not Be Empty',
                  ),
                  TextFormField(
                    controller: _courseController,
                    decoration: InputDecoration(labelText: 'Course'),
                    validator: (val) =>
                        val!.isNotEmpty ? null : 'Course Should Not Be Empty',
                  ),
                  ElevatedButton(
                      onPressed: () {
                        _submitStudent(context);
                      },
                      child: SizedBox(
                          width: MediaQuery.of(context).size.width * 0.9,
                          child: Text('Submit')),
                      style: ElevatedButton.styleFrom(
                          // primary: Colors.amber,
                          textStyle: TextStyle(color: Colors.white),
                          alignment: Alignment.center)),
                  FutureBuilder(
                      future: dbManager.getStudentList(),
                      builder: (context, AsyncSnapshot snapshot) {
                        if (snapshot.hasData) {
                          studlist = snapshot.data; //TODO
                          return ListView.builder(
                              //Acts as for loop
                              shrinkWrap: true,
                              itemCount: studlist!.length,
                              itemBuilder: (BuildContext context, int index) {
                                Student st = studlist![index]; //TODO
                                print(st
                                    .id); //! returning null on ID, but returning all 3 in st.course.
                                //! means ID is not being saved in DB.
                                return Card(
                                  child: Row(
                                    children: [
                                      SizedBox(
                                        width:
                                            MediaQuery.of(context).size.width *
                                                0.6,
                                        child: Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          children: [
                                            Text(
                                              'Name: ${st.name}',
                                              style: TextStyle(fontSize: 15),
                                            ),
                                            Text('Course: ${st.course}',
                                                style: TextStyle(
                                                    fontSize: 15,
                                                    color: Colors.black54)),
                                          ],
                                        ),
                                      ),
                                      IconButton(
                                          onPressed: () {
                                            _nameController.text = st.name;
                                            _courseController.text = st.course;
                                            //TODO
                                            student =
                                                st; //st assighned to global student object
                                            updateIndex = index;
                                          },
                                          icon: Icon(
                                            Icons.edit,
                                            color: Colors.blueAccent,
                                          )),
                                      IconButton(
                                          //TODO DELETE
                                          onPressed: () {
                                            // student =
                                            //     st; //st assighned to global student object
                                            // st.id = index;
                                            // print(
                                            //     'DELETE ID $index'); //! RETURNING 0,1,2 AS ID
                                            //TODO THE REAL PROBLEM IS st.id IS LIST ID, NOT THE ONE STORED IN DATABASE
                                            //TODO MEANS st.id IS WRONG. QUERY IS WRONG
                                            dbManager.deleteStudent(st
                                                .id!); //? Delete from Database
                                            //? id _CastError (Null check operator used on a null value)
                                            setState(() {
                                              studlist!.removeAt(
                                                  index); //? Remove from the List that is displayed
                                              // ! removing, but not from database. so it is comming back.
                                            });
                                          },
                                          icon: Icon(Icons.delete,
                                              color: Colors.red))
                                    ],
                                  ),
                                );
                              });
                        }
                        return CircularProgressIndicator();
                      })
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  void _submitStudent(BuildContext context) {
    if (_formKey.currentState!.validate()) {
      if (student == null) {
        Student st =
            Student(name: _nameController.text, course: _courseController.text);
        dbManager.insertStudent(st).then((id) {
          //! id is comming from here. cant be renamed to st.id
          setState(() {
            // st.id = id;
            _nameController.clear();
            _courseController.clear();
            // print('SUBMIT ID ${st.id}'); //! SUBMIT ID IS 13??? WHY/
            //! but st.id is null. Probably bcoz id can be null (int?) so it is null. But cant give required parameter as in name or course.
            //! ID is autoincrementing, but st.id is null. and ID is saved in database
          });
        });
      } else {
        // Student st =
        //     Student(name: _nameController.text, course: _courseController.text);

        student!.name = _nameController.text;
        student!.course = _courseController.text;
        // print(studlist);
        dbManager.updateStudent(student!).then((id) => {
              setState(() {
                studlist?[updateIndex!].name = _nameController.text;
                studlist?[updateIndex!].course = _courseController.text;
                print(studlist?[updateIndex!].course);
              }),
              _nameController.clear(),
              _courseController.clear(),
              student = null
            });
      }
    }
  }
}
